In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv('apple_quality.csv')
df

A_id      Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  \
0        0.0 -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840   
1        1.0 -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530   
2        2.0 -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033   
3        3.0 -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761   
4        4.0  1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849   
...      ...       ...       ...        ...          ...        ...       ...   
3996  3996.0 -0.293118  1.949253  -0.204020    -0.640196   0.024523 -1.087900   
3997  3997.0 -2.634515 -2.138247  -2.440461     0.657223   2.199709  4.763859   
3998  3998.0 -4.008004 -1.779337   2.366397    -0.200329   2.161435  0.214488   
3999  3999.0  0.278540 -1.715505   0.121217    -1.154075   1.266677 -0.776571   
4000     NaN       NaN       NaN        NaN          NaN        NaN       NaN   

                                Acidity Quality  
0                          -0.491590483    good  
1                          -0.722809367    good  
2                           2.621636473     bad  
3                           0.790723217    good  
4                           0.501984036    good  
...                                 ...     ...  
3996                        1.854235285    good  
3997                       -1.334611391     bad  
3998                       -2.229719806    good  
3999                        1.599796456    good  
4000  Created_by_Nidula_Elgiriyewithana     NaN  

[4001 rows x 9 columns]

In [3]:
df.head()

A_id      Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  \
0   0.0 -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840   
1   1.0 -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530   
2   2.0 -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033   
3   3.0 -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761   
4   4.0  1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849   

        Acidity Quality  
0  -0.491590483    good  
1  -0.722809367    good  
2   2.621636473     bad  
3   0.790723217    good  
4   0.501984036    good

In [4]:
df.tail()

A_id      Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  \
3996  3996.0 -0.293118  1.949253  -0.204020    -0.640196   0.024523 -1.087900   
3997  3997.0 -2.634515 -2.138247  -2.440461     0.657223   2.199709  4.763859   
3998  3998.0 -4.008004 -1.779337   2.366397    -0.200329   2.161435  0.214488   
3999  3999.0  0.278540 -1.715505   0.121217    -1.154075   1.266677 -0.776571   
4000     NaN       NaN       NaN        NaN          NaN        NaN       NaN   

                                Acidity Quality  
3996                        1.854235285    good  
3997                       -1.334611391     bad  
3998                       -2.229719806    good  
3999                        1.599796456    good  
4000  Created_by_Nidula_Elgiriyewithana     NaN

In [5]:
df.shape

(4001, 9)

In [6]:
df.columns

Index(['A_id', 'Size', 'Weight', 'Sweetness', 'Crunchiness', 'Juiciness',
       'Ripeness', 'Acidity', 'Quality'],
      dtype='object')

In [7]:
df.dtypes

A_id           float64
Size           float64
Weight         float64
Sweetness      float64
Crunchiness    float64
Juiciness      float64
Ripeness       float64
Acidity         object
Quality         object
dtype: object

In [8]:
df.drop(['A_id'],axis=1,inplace=True)

In [9]:
df.isna().sum()

Size           1
Weight         1
Sweetness      1
Crunchiness    1
Juiciness      1
Ripeness       1
Acidity        0
Quality        1
dtype: int64

In [10]:
df['Size'].unique()

array([-3.97004852, -1.19521719, -0.29202386, ..., -4.00800374,
        0.27853965,         nan], shape=(4001,))

In [11]:
df['Weight'].unique()

array([-2.51233638, -2.83925653, -1.35128199, ..., -1.77933711,
       -1.71550503,         nan], shape=(4001,))

In [12]:
df['Sweetness'].unique()

array([ 5.34632961,  3.66405876, -1.73842916, ...,  2.36639697,
        0.12121725,         nan], shape=(4001,))

In [13]:
df['Crunchiness'].unique()

array([-1.01200871,  1.58823231, -0.34261593, ..., -0.20032937,
       -1.15407476,         nan], shape=(4001,))

In [14]:
df['Juiciness'].unique()

array([1.84490036, 0.8532858 , 2.83863551, ..., 2.16143512, 1.2666774 ,
              nan], shape=(4001,))

In [15]:
df['Ripeness'].unique()

array([ 0.3298398 ,  0.86753008, -0.03803333, ...,  0.21448838,
       -0.77657147,         nan], shape=(4001,))

In [16]:
df['Quality'].unique()

array(['good', 'bad', nan], dtype=object)

In [17]:
df['Size']=df['Size'].fillna(df['Size'].mode()[0])
df['Weight']=df['Weight'].fillna(df['Weight'].mode()[0])
df['Sweetness']=df['Sweetness'].fillna(df['Sweetness'].mode()[0])
df['Crunchiness']=df['Crunchiness'].fillna(df['Crunchiness'].mode()[0])
df['Juiciness']=df['Juiciness'].fillna(df['Juiciness'].mode()[0])
df['Ripeness']=df['Ripeness'].fillna(df['Ripeness'].mode()[0])
df['Quality']=df['Quality'].fillna(df['Quality'].mode()[0])


In [18]:
df.isna().sum()

Size           0
Weight         0
Sweetness      0
Crunchiness    0
Juiciness      0
Ripeness       0
Acidity        0
Quality        0
dtype: int64

In [19]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Acidity']=lab.fit_transform(df['Acidity'])

In [20]:
df.dtypes

Size           float64
Weight         float64
Sweetness      float64
Crunchiness    float64
Juiciness      float64
Ripeness       float64
Acidity          int64
Quality         object
dtype: object

In [21]:
x=df.iloc[:,:-1].values
x

array([[-3.97004852e+00, -2.51233638e+00,  5.34632961e+00, ...,
         1.84490036e+00,  3.29839797e-01,  3.97000000e+02],
       [-1.19521719e+00, -2.83925653e+00,  3.66405876e+00, ...,
         8.53285795e-01,  8.67530082e-01,  5.50000000e+02],
       [-2.92023862e-01, -1.35128199e+00, -1.73842916e+00, ...,
         2.83863551e+00, -3.80333280e-02,  3.54300000e+03],
       ...,
       [-4.00800374e+00, -1.77933711e+00,  2.36639697e+00, ...,
         2.16143512e+00,  2.14488384e-01,  1.42800000e+03],
       [ 2.78539650e-01, -1.71550503e+00,  1.21217251e-01, ...,
         1.26667740e+00, -7.76571470e-01,  3.04100000e+03],
       [-7.15170306e+00, -7.14984768e+00, -6.89448549e+00, ...,
        -5.96189705e+00, -5.86459892e+00,  4.00000000e+03]],
      shape=(4001, 7))

In [22]:
y=df.iloc[:,-1]
y

0       good
1       good
2        bad
3       good
4       good
        ... 
3996    good
3997     bad
3998    good
3999    good
4000    good
Name: Quality, Length: 4001, dtype: object

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [24]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_test)
x_train=scaler.transform(x_train)
x__test=scaler.transform(x_test)
x_train

array([[-1.80494978,  0.31550366,  1.74549585, ...,  1.10213058,
        -0.64493744, -0.20677284],
       [ 0.76555321,  0.33053986, -0.53075019, ...,  0.17563273,
         0.15575139, -1.19854216],
       [-0.34573612,  0.62278583,  0.6939922 , ...,  1.11251773,
        -0.61938619, -0.1140112 ],
       ...,
       [ 1.54941703, -0.38061557,  0.11269558, ..., -0.89988275,
         2.05904154,  0.71044039],
       [-0.65147108, -0.07384109,  1.08217426, ..., -0.02324913,
        -0.04893154, -1.22541703],
       [-0.67270152,  1.45550241,  0.39510188, ...,  0.64567479,
        -0.99315432, -0.81709242]], shape=(2800, 7))

In [25]:
x_test

array([[ 3.09941064e+00, -1.69156068e+00, -3.67936400e+00, ...,
         5.38102393e-01,  1.66009938e+00,  4.38000000e+02],
       [-1.65601234e+00, -2.31805555e+00, -2.61834519e+00, ...,
         2.31202226e+00,  4.11602944e+00,  2.53600000e+03],
       [ 1.20678634e+00, -5.08979201e-01,  1.73620694e+00, ...,
        -5.56148589e-01, -1.33205168e+00,  2.69200000e+03],
       ...,
       [ 1.15748710e-01, -1.42796383e+00, -3.18072175e+00, ...,
        -1.31869702e+00,  3.46146570e+00,  6.87000000e+02],
       [-1.57282776e+00, -8.16051422e-01, -1.65678940e-01, ...,
         3.58000165e-01,  1.66217926e+00,  1.61700000e+03],
       [-1.41911268e-01, -1.15284238e+00, -3.63652623e+00, ...,
         1.56486730e+00,  4.20053840e+00,  1.02100000e+03]],
      shape=(1201, 7))

In [26]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array(['good', 'good', 'good', ..., 'good', 'good', 'good'],
      shape=(1201,), dtype=object)

In [27]:
y_test

555     good
2793     bad
527      bad
3871     bad
2990     bad
        ... 
2011    good
226      bad
1613     bad
535     good
3352     bad
Name: Quality, Length: 1201, dtype: object

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[  1, 605],
       [  0, 595]])

In [29]:
acc=accuracy_score(y_test,y_pred)
acc

0.4962531223980017

In [30]:
print(model.predict(scaler.transform([[-1,0,4,2,0,0,2]])))

['good']


In [31]:
df

Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  \
0    -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840   
1    -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530   
2    -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033   
3    -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761   
4     1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849   
...        ...       ...        ...          ...        ...       ...   
3996 -0.293118  1.949253  -0.204020    -0.640196   0.024523 -1.087900   
3997 -2.634515 -2.138247  -2.440461     0.657223   2.199709  4.763859   
3998 -4.008004 -1.779337   2.366397    -0.200329   2.161435  0.214488   
3999  0.278540 -1.715505   0.121217    -1.154075   1.266677 -0.776571   
4000 -7.151703 -7.149848  -6.894485    -6.055058  -5.961897 -5.864599   

      Acidity Quality  
0         397    good  
1         550    good  
2        3543     bad  
3        2550    good  
4        2344    good  
...       ...     ...  
3996     3177    good  
3997      943     bad  
3998     1428    good  
3999     3041    good  
4000     4000    good  

[4001 rows x 8 columns]

In [32]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

         bad       1.00      0.00      0.00       606
        good       0.50      1.00      0.66       595

    accuracy                           0.50      1201
   macro avg       0.75      0.50      0.33      1201
weighted avg       0.75      0.50      0.33      1201

